package com.example.constant.sql;

public class EmployeeSqlConstant {

	public static final String INSERT_EMPLOYEES = "INSERT INTO HR.EMPLOYEES(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static final String UPDATE_EMPLOYEES = "UPDATE HR.EMPLOYEES SET FIRST_NAME = ?, LAST_NAME = ?, EMAIL = ?, PHONE_NUMBER = ?, HIRE_DATE = ?, JOB_ID = ?, SALARY = ?, COMMISSION_PCT = ?, MANAGER_ID = ?, DEPARTMENT_ID = ? WHERE EMPLOYEE_ID = ?";
	public static final String LIST_EMPLOYEES = "SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID FROM HR.EMPLOYEES ORDER BY HR.EMPLOYEES.EMPLOYEE_ID ASC";
	public static final String GET_EMPLOYEES_BY_EMPLOYEEID = "SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID FROM HR.EMPLOYEES WHERE EMPLOYEE_ID = ?";
	public static final String DELETE_EMPLOYEES_BY_EMPLOYEEID = "DELETE HR.EMPLOYEES WHERE EMPLOYEE_ID = ?";

}
