package com.example.constant.sql;

public class UserSqlConstant {
	public static final String GET_USER_BY_USERNAME = "SELECT U.USID, U.USACCEXPDATE, U.USNAME, U.USUSERID, U.USENABLED, U.USPASSWORD, "+
			" U.USEMAIL, U.USCRENONEXP, U.USCREEXPDATE, U.USACCNONLOC, U.USACCNONEXP, U.USACCEXPDATE FROM HR.T_USER U WHERE U.USEMAIL = ? ";
}
